---

version: "2"

services:
  site:
    image: ${DOCKER_USER}/montdenis
    labels:
      traefik.http.routers.montdenis-http.rule: Host(`pension.montdenis.fr`)
      traefik.http.routers.montdenis-http.entrypoints: http
      traefik.http.routers.montdenis-http.middlewares: redirect@file
      traefik.http.routers.montdenis-https.rule: Host(`pension.montdenis.fr`)
      traefik.http.routers.montdenis-https.entrypoints: https
      traefik.http.routers.montdenis-https.middlewares: compress@file, web-limit@file
      traefik.http.routers.montdenis-https.tls: "true"
      traefik.http.routers.montdenis-https.tls.certresolver: default
      traefik.http.services.montdenis-service.loadbalancer.server.port: "1080"
    environment:
      VIWS_CSP: "default-src 'self'; base-uri 'self'; script-src 'self' 'unsafe-inline' *.mapbox.com; style-src 'self' 'unsafe-inline' cdn.jsdelivr.net/npm/normalize.css@8.0.0/ *.mapbox.com; img-src 'self' data: blob: ; child-src 'self' blob:; worker-src 'self' blob:; connect-src 'self' *.mapbox.com"
      VIWS_HEADERS: X-UA-Compatible:ie=edge~content-language:fr
    restart: on-failure:5
    read_only: true
    cpu_shares: 128
    mem_limit: 67108864
    security_opt:
      - no-new-privileges
